import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Real catalog, dumped directly from evlv-site's src/lib/products.ts (see
// prisma/evlv-catalog.json -- generated by exporting that file's `products`
// array to JSON, so slug/sku/name/price/content can never drift from a
// hand-copied placeholder list again; re-generate that JSON + re-run this
// seed any time products.ts changes). Every one of its dose variants gets
// a real Product + StoreMapping row here, with real marketing content
// (photo, descriptions, purity, storage/recon copy) so the CRM is an
// actual source of truth for the storefront instead of a checkout-only
// price/stock shadow of it. cogsCents/masterStock are still estimates (30%
// of price, 150 units) since real cost/inventory numbers weren't available
// here -- correct those two columns (or edit them per-product in the CRM
// UI) once you have the real figures. Safe to re-run any time, it's all
// upserts.
import catalogJson from "./evlv-catalog.json";

interface StaticProduct {
  slug: string;
  sku: string;
  name: string;
  price: number;
  image?: string;
  purity?: string;
  categoryLabel?: string;
  shortDescription: string;
  description: string;
  storage: string;
  reconstitution?: string;
}

const STORE_DOMAIN = "evlvpeptides.com";
const catalog = catalogJson as unknown as StaticProduct[];

const PRODUCTS = catalog.map((p) => ({
  slug: p.slug,
  sku: p.sku,
  chemicalName: p.name,
  priceCents: Math.round(p.price * 100),
  imageUrl: p.image ? ("https://" + STORE_DOMAIN + p.image) : undefined,
  shortDescription: p.shortDescription as string | undefined,
  description: p.description as string | undefined,
  purity: p.purity,
  categoryLabel: p.categoryLabel,
  storageInstructions: p.storage as string | undefined,
  reconstitutionInstructions: p.reconstitution,
}));

// Required reconstitution add-on, auto-included by evlv-site's cart on
// every order -- see BAC_WATER in evlv-site's src/lib/cart-context.tsx,
// whose comment points back at this exact file/slug. Not part of
// products.ts's own catalog (it's a cart-level add-on, not a shop
// product), so it stays hand-listed here.
PRODUCTS.push({
  slug: "bacteriostatic-water-30ml",
  sku: "BAC-WATER-30ML",
  chemicalName: "Bacteriostatic Water 30mL",
  priceCents: 1500,
  imageUrl: undefined,
  shortDescription: "Sterile bacteriostatic water for reconstituting lyophilized research peptides.",
  description: "Bacteriostatic water, 30mL, for laboratory reconstitution use only.",
  purity: undefined,
  categoryLabel: "Ancillaries",
  storageInstructions: "Store at room temperature, away from direct light. Refrigerate after opening.",
  reconstitutionInstructions: undefined,
});

async function main() {
  const org = await prisma.organization.upsert({
    where: { slug: "evlv" },
    update: { notifyEmail: "office@evlvpeptides.com" },
    create: { name: "EVLV", slug: "evlv", plan: "GROWTH", notifyEmail: "office@evlvpeptides.com" },
  });

  const brand = await prisma.brand.upsert({
    where: { organizationId_slug: { organizationId: org.id, slug: "evlv" } },
    update: { domain: "evlvpeptides.com", status: "CONNECTED" },
    create: {
      organizationId: org.id,
      slug: "evlv",
      name: "EVLV",
      domain: "evlvpeptides.com",
      status: "CONNECTED",
      verifiedAt: new Date(),
    },
  });

  const passwordHash = await bcrypt.hash("password123", 10);
  const staffUser = await prisma.user.upsert({
    where: { email: "operator@evlvpeptides.com" },
    update: {},
    create: { email: "operator@evlvpeptides.com", name: "EVLV Operator", passwordHash },
  });
  await prisma.membership.upsert({
    where: { userId_organizationId: { userId: staffUser.id, organizationId: org.id } },
    update: {},
    create: { userId: staffUser.id, organizationId: org.id, role: "OWNER" },
  });

  // Deactivate any leftover mapping from the old placeholder catalog (e.g.
  // "bpc-157-5mg", "tb-500-5mg") that isn't a real evlv-site slug — left in
  // place (not deleted) since a placed order may already reference the
  // underlying Product row.
  const realSlugs = PRODUCTS.map((p) => p.slug);
  await prisma.storeMapping.updateMany({
    where: { brandId: brand.id, slug: { notIn: realSlugs } },
    data: { active: false },
  });

  for (const p of PRODUCTS) {
    const masterStock = 150;
    const cogsCents = Math.round(p.priceCents * 0.3);

    const product = await prisma.product.upsert({
      where: { organizationId_sku: { organizationId: org.id, sku: p.sku } },
      update: {
        chemicalName: p.chemicalName,
        cogsCents,
        imageUrl: p.imageUrl,
        shortDescription: p.shortDescription,
        description: p.description,
        purity: p.purity,
        categoryLabel: p.categoryLabel,
        storageInstructions: p.storageInstructions,
        reconstitutionInstructions: p.reconstitutionInstructions,
      },
      create: {
        organizationId: org.id,
        sku: p.sku,
        chemicalName: p.chemicalName,
        cogsCents,
        masterStock,
        imageUrl: p.imageUrl,
        shortDescription: p.shortDescription,
        description: p.description,
        purity: p.purity,
        categoryLabel: p.categoryLabel,
        storageInstructions: p.storageInstructions,
        reconstitutionInstructions: p.reconstitutionInstructions,
      },
    });

    await prisma.storeMapping.upsert({
      where: { brandId_slug: { brandId: brand.id, slug: p.slug } },
      update: { storePriceCents: p.priceCents, active: true },
      create: {
        productId: product.id,
        brandId: brand.id,
        externalProductId: p.slug,
        slug: p.slug,
        storePriceCents: p.priceCents,
        active: true,
      },
    });

    await prisma.productLot.upsert({
      where: { productId_lotNumber: { productId: product.id, lotNumber: `LOT-${p.sku}-001` } },
      update: {},
      create: {
        productId: product.id,
        lotNumber: `LOT-${p.sku}-001`,
        quantityReceived: masterStock,
        quantityRemaining: masterStock,
      },
    });
  }

  // Contact-form submissions (see /api/forms/submit) are gated by this
  // public key, not the org api key -- it's meant to be embeddable
  // client-side, but evlv-site proxies it server-side anyway to keep
  // CRM_API_URL itself out of the browser bundle. See evlv-site's
  // src/app/api/contact/route.ts.
  const trackingConfig = await prisma.trackingConfig.upsert({
    where: { brandId: brand.id },
    update: {},
    create: { brandId: brand.id },
  });

  // A real, working affiliate account to test the whole self-serve portal
  // flow with immediately (apply/login already exists here, pre-approved).
  // Change this password after first real login.
  const affiliatePassword = "Evlv2026-Aff!qX8mK";
  const affiliatePasswordHash = await bcrypt.hash(affiliatePassword, 10);
  const affiliate = await prisma.affiliate.upsert({
    where: { email: "nikolazivkovic0803@gmail.com" },
    update: { status: "APPROVED" },
    create: {
      organizationId: org.id,
      name: "Nikola",
      slug: "NIKOLA",
      couponCode: "NIKOLA",
      ratePercent: 20,
      status: "APPROVED",
      email: "nikolazivkovic0803@gmail.com",
      passwordHash: affiliatePasswordHash,
      username: "nikola",
      firstName: "Nikola",
    },
  });

  console.log("EVLV seed complete.");
  console.log(`  Organization: ${org.name} (${org.id})`);
  console.log(`  Brand domain: ${brand.domain}`);
  console.log(`  CRM_ORG_API_KEY=${org.apiKey}`);
  console.log(`  CRM_STORE_DOMAIN=${brand.domain}`);
  console.log(`  CRM_CONTACT_FORM_KEY=${trackingConfig.publicKey}`);
  console.log("  Staff login: operator@evlvpeptides.com / password123");
  console.log(`  Affiliate portal login (https://evlvpeptides.com/affiliates/login): ${affiliate.email} / ${affiliatePassword}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
