import { notFound } from "next/navigation";
import Link from "next/link";
import { requireOrg } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { PageHeader, Card, Badge, StatCard, EmptyState } from "@/components/ui";
import { money, shortDate, dateTime } from "@/lib/format";
import { setInvoiceStatus } from "../actions";
import { SupplierImportForm } from "./import-form";

const LOW_STOCK_THRESHOLD = 10;

export default async function SupplierDetailPage({ params }: { params: { id: string } }) {
  const { organization } = await requireOrg();

  const supplier = await prisma.supplier.findFirst({
    where: { id: params.id, organizationId: organization.id },
    include: {
      products: { include: { product: true }, orderBy: { updatedAt: "desc" } },
      invoices: { orderBy: { createdAt: "desc" }, include: { lineItems: true } },
    },
  });
  if (!supplier) notFound();

  const owed = supplier.invoices.filter((i) => i.status !== "PAID").reduce((s, i) => s + i.totalCents, 0);
  const lowStock = supplier.products.filter((p) => p.active && p.stock <= LOW_STOCK_THRESHOLD);

  return (
    <div>
      <PageHeader
        title={supplier.name}
        subtitle={supplier.contactEmail || "No contact email"}
        actions={
          <Link href="/suppliers" className="text-sm border border-background-300 rounded-md px-3 py-1.5 text-foreground-700 hover:bg-background-100">
            Back
          </Link>
        }
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <StatCard label="Outstanding" value={money(owed)} hint="Unpaid invoices" />
        <StatCard label="Active products" value={String(supplier.products.filter((p) => p.active).length)} />
        <StatCard label="Low stock" value={String(lowStock.length)} hint={`≤ ${LOW_STOCK_THRESHOLD} units`} />
      </div>

      {lowStock.length > 0 && (
        <Card className="p-4 mb-6 border-accent-300 bg-accent-50">
          <p className="text-sm font-semibold text-accent-800 mb-1">Low stock</p>
          <ul className="text-xs text-accent-800 space-y-0.5">
            {lowStock.map((p) => (
              <li key={p.id}>
                {p.product.chemicalName} ({p.product.sku}) — {p.stock} left
              </li>
            ))}
          </ul>
        </Card>
      )}

      <Card className="p-4">
        <h2 className="text-sm font-semibold text-foreground-950 mb-3">Invoices</h2>
        {supplier.invoices.length === 0 ? (
          <EmptyState icon="ri-bill-line" title="No invoices yet" body="Nothing generated by this supplier yet." />
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-foreground-500 border-b border-background-200">
                <th className="py-1.5 font-medium">Period</th>
                <th className="py-1.5 font-medium">Items</th>
                <th className="py-1.5 font-medium text-right">Total</th>
                <th className="py-1.5 font-medium">Status</th>
                <th className="py-1.5 font-medium"></th>
              </tr>
            </thead>
            <tbody>
              {supplier.invoices.map((inv) => (
                <tr key={inv.id} className="border-b border-background-100 last:border-0">
                  <td className="py-2 text-foreground-800">
                    {shortDate(inv.periodStart)} – {shortDate(inv.periodEnd)}
                  </td>
                  <td className="py-2 tabular-nums">{inv.lineItems.length}</td>
                  <td className="py-2 text-right tabular-nums font-medium">{money(inv.totalCents)}</td>
                  <td className="py-2">
                    <Badge status={inv.status} />
                  </td>
                  <td className="py-2 text-right">
                    {inv.status === "DRAFT" && (
                      <form action={setInvoiceStatus.bind(null, inv.id, "SENT")}>
                        <button className="text-xs text-primary-600 hover:underline">Mark sent</button>
                      </form>
                    )}
                    {inv.status === "SENT" && (
                      <form action={setInvoiceStatus.bind(null, inv.id, "PAID")}>
                        <button className="text-xs text-primary-600 hover:underline">Mark paid</button>
                      </form>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>

      <Card className="p-4 mt-4">
        <div className="flex items-start justify-between gap-4 mb-3">
          <div>
            <h2 className="text-sm font-semibold text-foreground-950">Products</h2>
            <p className="text-xs text-foreground-500 mt-0.5">
              Pre-fill his price list before he has a login — CSV with header row{" "}
              <code className="font-mono">sku,wholesale,name,mg</code> (only sku + wholesale required; unknown SKUs
              get added to the master catalog).
            </p>
          </div>
          <div className="w-64 shrink-0">
            <SupplierImportForm supplierId={supplier.id} />
          </div>
        </div>
        {supplier.products.length === 0 ? (
          <p className="text-xs text-foreground-500">No products listed yet.</p>
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-foreground-500 border-b border-background-200">
                <th className="py-1.5 font-medium">Product</th>
                <th className="py-1.5 font-medium">SKU</th>
                <th className="py-1.5 font-medium text-right">Cost</th>
                <th className="py-1.5 font-medium text-right">Shipping</th>
                <th className="py-1.5 font-medium text-right">Stock</th>
                <th className="py-1.5 font-medium">Status</th>
                <th className="py-1.5 font-medium">Updated</th>
              </tr>
            </thead>
            <tbody>
              {supplier.products.map((p) => (
                <tr key={p.id} className="border-b border-background-100 last:border-0">
                  <td className="py-2 text-foreground-800">{p.product.chemicalName}</td>
                  <td className="py-2 font-mono text-xs text-foreground-600">{p.product.sku}</td>
                  <td className="py-2 text-right tabular-nums">{money(p.costCents)}</td>
                  <td className="py-2 text-right tabular-nums">{money(p.shippingCents)}</td>
                  <td className={`py-2 text-right tabular-nums ${p.stock <= LOW_STOCK_THRESHOLD ? "text-accent-700 font-medium" : ""}`}>{p.stock}</td>
                  <td className="py-2">
                    <Badge status={p.active ? "connected" : "pending"} />
                  </td>
                  <td className="py-2 text-xs text-foreground-500">{dateTime(p.updatedAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>
    </div>
  );
}
